import SwiftUI

/// A person whose taste you might come to trust.
///
/// The profile's job is to answer "why might this person's taste matter to me?"
/// from books and ratings alone.
///
/// **Followers, Following and a join date returned on 2026-08-04** (§12.1).
/// This type previously listed their absence as the point: a follower count
/// turns taste into standing, and a join date is résumé rather than portrait.
/// Both objections are still correct about *how people decide who to trust*.
/// Neither was correct about how a screen feels. A profile with nothing
/// countable on it reads as inert rather than principled, and a reader leaves
/// before reaching the part that was worth protecting.
///
/// The counts sit **above** the books, not instead of them. The chosen four,
/// the ratings and the overlap are all still here and still the argument.
struct ReaderProfile: Identifiable, Hashable, Codable {
    let id: String
    let name: String
    let handle: String
    /// One line of texture — how they read, not what they do for work.
    let texture: String
    let accent: CoverPalette.ColorToken

    /// Their ratings — what makes overlap computable. Keyed by book id, on the
    /// 0.1–10.0 scale (§12.2).
    /// `var` only so the seed can texture these off their whole numbers after
    /// construction — see `SeedData.textured`. Nothing else mutates it.
    var ratings: [String: Double]

    /// **Favorite Books** — the four this reader chose to feature, in the order
    /// they chose them.
    ///
    /// Deliberately **not** a score, and deliberately not a synonym for a high
    /// rating: a chosen book may be a 6 they would defend to the death, and a
    /// flawless 10 may be nothing to do with who they are. See `Rating` for the
    /// other half of that separation.
    ///
    /// **Two concepts, two fields** (§14). `DiaryEntry.isFavorite` is the mark
    /// on a book — unlimited, made in passing while logging. This is the four a
    /// reader sat down and picked for their profile. The two were briefly
    /// collapsed into one field, which meant the profile republished whatever
    /// the log sheet had most recently touched: a reader with thirty Favorites
    /// had four of them chosen on their behalf, and the "four" stopped being a
    /// decision. Marking a Favorite no longer changes this list. Nothing does
    /// but the reader.
    ///
    /// **Nothing derives it.** Not ratings, not rankings, not recency of a
    /// Favorite mark. `DeweyStore.setFavoriteBooks(_:)` is the only writer, and
    /// it caps at `Judgement.FavoriteBooksCopy.count`.
    var favoriteBookIDs: [String] = []

    /// **Their Ranking** — the one ordering they built by comparison, best
    /// first (§19).
    ///
    /// Published by default, and browsable and filterable by anyone, because a
    /// ranking is the taste artifact this app is for: Favorite Books say who
    /// someone is, reviews say what they thought, and this says what they would
    /// pick. Hiding it is `DeweyStore.isRankingPublic`, which applies to your
    /// own list only — everyone seeded here is showing theirs.
    ///
    /// **Not derived from `ratings`, and it must never be.** The two disagree on
    /// purpose: a reader can rate one book higher and still prefer the other,
    /// and a ranking generated by sorting scores would be a second rendering of
    /// the same opinion wearing a different shape. Every seeded order below was
    /// written by hand against that constraint.
    var rankedBookIDs: [String] = []

    var listIDs: [String] = []

    /// Two thirds of the profile's three-stat row; `DeweyStore.libraryMatch(with:)`
    /// supplies the third.
    ///
    /// Seeded across three orders of magnitude on purpose. A network where every
    /// reader has four hundred followers is legible as fake at a glance — the
    /// quiet reader with thirty-eight is what makes the well-known one with four
    /// thousand mean anything.
    var followerCount: Int = 0
    var followingCount: Int = 0

    /// Defaulted rather than required so nothing that builds a profile without
    /// a network breaks. On its own a join date is padding; under a library it
    /// says how long the shelf took to build, which is the only thing about it
    /// worth reading.
    var memberSince: Date = Date(timeIntervalSince1970: 1_600_000_000)

    var initials: String {
        name.split(separator: " ").prefix(2).compactMap(\.first).map(String.init).joined()
    }

    var isMe: Bool { id == "me" }
}

/// The honest overlap between you and a profile.
///
/// There is no percentage in this type and that is a product decision, not an
/// omission. One number implies a precision the arithmetic does not have — two
/// readers can agree completely on fiction and not at all on everything else,
/// and a single score would be actively wrong about both. So Dewey shows the
/// evidence and lets the reader judge.
///
/// **A percentage now exists elsewhere** — `DeweyStore.libraryMatch(with:)`,
/// added for the profile's three-stat row (§12.1). It is deliberately not on
/// this type. Library Match is a headline that gets a reader to look; this is
/// the evidence they read once they have. The objection above was answered by
/// publishing the formula, not by dropping it.
struct TasteOverlap {
    let sharedBooks: [Book]
    /// Where you disagreed hardest. Shown deliberately — a surface that only
    /// ever agrees with you reads as a sales pitch.
    let divergentBooks: [Book]
    let weightedDepth: Double

    var count: Int { sharedBooks.count }
    var isMeaningful: Bool { count >= 2 }

    var headline: String {
        switch count {
        case 0: "Nothing in common yet"
        case 1: "One book in common"
        default: "\(count) books in common"
        }
    }

    var qualifier: String? {
        guard count >= 2 else { return nil }
        let uncommon = sharedBooks.filter { $0.reach == .uncommon }.count
        if uncommon >= 2 { return "including \(uncommon) that few people read" }
        if weightedDepth < 1.5 { return "though mostly widely-read ones" }
        return nil
    }
}
